[data]
num_nodes = 165
lag = 7
horizon = 4
val_ratio = 1
test_ratio = 1
tod = False
normalizer = std
column_wise = False
feature_wise = True
data_dir = C:\Users\30922\Desktop\AddPiData\BestGIS\NADE-main\data

[model]
input_dim = 11
output_dim = 1
embed_dim = 8
hidden_dim = 80
alpha = 0.2
time_dependence = True
time_divided = False
model_type = AD
transformer_heads = 6
transformer_dropout = 0.01

[train]
loss_func = mse
seed = 3407
batch_size = 16
epochs = 15
lr_init = 0.0019000000000000002
lr_decay = True
lr_decay_rate = 0.5
lr_decay_step = 20,40,70,130,190,250,280,295
early_stop = True
early_stop_patience = 5000
grad_norm = False
max_grad_norm = 5
real_value = False
dropout_rate = 0.02
r_drop_beta = 9.1

[test]
mae_thresh = None
mape_thresh = 0.

[log]
log_step = 1
plot = True

